package: search_it
version: '6.9.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/search_it


page:
    title: 'translate:title'
    perm: search_it[]
    pjax: false
    icon: rex-icon fa-search
    subpages:
        generate: { title: 'translate:generate', perm: search_it[generate], icon: rex-icon fa-tasks }
        settings:
            title: 'translate:settings'
            perm: search_it[settings]
            icon: rex-icon fa-wrench
            subpages:
                         mode: { title: 'translate:settings_mode' }
                         result: { title: 'translate:settings_result' }
                         addsources: { title: 'translate:settings_addsources' }
                         blacklist: { title: 'translate:settings_blacklist' }
        test: { title: 'translate:test', icon: rex-icon fa-flask }

console_commands:
    search_it:reindex: rex_search_it_command_reindex

requires:
    redaxo: '^5.5.0'
    php: '>=7'

system_plugins:
    - documentation

plugins:
    - plaintext
    - stats

installer_ignore:
    - .github
    - .gitignore
    - .php-cs-fixer.cache
    - .php-cs-fixer.dist.php
    - psalm.xml
