package: search_it
version: '6.14.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/search_it

mysql_insert_chunk_size: 100

page:
    title: 'translate:title'
    perm: search_it[]
    pjax: false
    icon: rex-icon fa-search
    subpages:
        generate: { title: 'translate:generate', perm: "search_it[ generate ]", icon: rex-icon fa-tasks }
        settings:
            title: 'translate:settings'
            perm: search_it[settings]
            icon: rex-icon fa-wrench
            subpages:
                mode: { title: 'translate:settings_mode' }
                result: { title: 'translate:settings_result' }
                addsources: { title: 'translate:settings_addsources' }
                blacklist: { title: 'translate:settings_blacklist' }
        suggest: { title: 'translate:search_it_autocomplete_title', icon: rex-icon fa-commenting }
        plaintext: { title: 'translate:search_it_plaintext_title', icon: rex-icon fa-file-text }
        stats: { title: 'translate:search_it_stats_plugin_title', icon: rex-icon fa-bar-chart }
        test: { title: 'translate:test', icon: rex-icon fa-flask }
        docs:
            title: 'translate:search_it_docs'
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: search_it[docs]



console_commands:
    search_it:reindex: FriendsOfREDAXO\SearchIt\Command\Reindex
    search_it:clearCache: FriendsOfREDAXO\SearchIt\Command\ClearCache

requires:
    redaxo: '^5.6.0'
    php: '>=7'
    php_extensions:
        - gd

installer_ignore:
    - .github
    - .gitignore
    - .php-cs-fixer.cache
    - .php-cs-fixer.dist.php
    - psalm.xml
