DROP TABLE IF EXISTS `%TABLE_PREFIX%%TMP_PREFIX%search_it_index`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%%TMP_PREFIX%search_it_cache`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%%TMP_PREFIX%search_it_cacheindex_ids`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%%TMP_PREFIX%search_it_keywords`;
